name: CI

on:
  push:
    branches: [main, master]
  pull_request:
  workflow_dispatch:

jobs:
  rust:
    name: Rust Lint & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: cargo fmt --check
        working-directory: rust
        run: cargo fmt --all -- --check

      - name: cargo clippy
        working-directory: rust
        run: cargo clippy --all-targets -- -D warnings

      - name: cargo test
        working-directory: rust
        run: cargo test --all

  cpp:
    name: C++ Build
    runs-on: ubuntu-latest
    needs: rust
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo target
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: rust

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build pkg-config libfcitx5core-dev

      - name: Configure CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G Ninja

      - name: Build addon
        run: cmake --build build --parallel
